// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUhTlRJzL7mdzMrqSFitVb_xEnKrIAYs4',
    appId: '1:1045098359995:web:dfc050fe054ca7609dcd9e',
    messagingSenderId: '1045098359995',
    projectId: 'minotes',
    authDomain: 'minotes.firebaseapp.com',
    storageBucket: 'minotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGr_gkNsLENxNsPZAUe0M9IrBF9WgXj_c',
    appId: '1:1045098359995:android:eae826070d5dc5539dcd9e',
    messagingSenderId: '1045098359995',
    projectId: 'minotes',
    storageBucket: 'minotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiDQszk9bnbEf9b00DwQV42Q3kKU2H2ss',
    appId: '1:1045098359995:ios:ddfe3dfb9b5b94179dcd9e',
    messagingSenderId: '1045098359995',
    projectId: 'minotes',
    storageBucket: 'minotes.appspot.com',
    iosClientId: '1045098359995-i10593tm1lk7d58oiirbr2qr6lv1j2jj.apps.googleusercontent.com',
    iosBundleId: 'com.example.minotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiDQszk9bnbEf9b00DwQV42Q3kKU2H2ss',
    appId: '1:1045098359995:ios:ddfe3dfb9b5b94179dcd9e',
    messagingSenderId: '1045098359995',
    projectId: 'minotes',
    storageBucket: 'minotes.appspot.com',
    iosClientId: '1045098359995-i10593tm1lk7d58oiirbr2qr6lv1j2jj.apps.googleusercontent.com',
    iosBundleId: 'com.example.minotes',
  );
}
